env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64
    ldflags:
      - -X github.com/bizflycloud/bizfly-backup/cmd.version={{ .Version }}
      - -X github.com/bizflycloud/bizfly-backup/cmd.gitCommit={{ .ShortCommit }}
      - -X github.com/bizflycloud/bizfly-backup/pkg/server.Version={{ .Version }}
      - -X github.com/bizflycloud/bizfly-backup/pkg/agentversion.version={{ .Version }}
      - -X github.com/bizflycloud/bizfly-backup/pkg/agentversion.commit={{ .ShortCommit }}
      - -X github.com/bizflycloud/bizfly-backup/pkg/agentversion.buildTime={{ .Date }}
    main: main.go
    binary: bizfly-backup
    hooks:
      pre: make build
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

source:
  enabled: true
  rlcp: true
  name_template: '{{ .ProjectName }}'
  format: 'tar'
release:
  github:
    owner: bizflycloud
    name: bizfly-backup
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
